@startuml
'https://plantuml.com/class-diagram

class Produto {
    - preco: Double
    - nome: String
    - quatidade: Integer
}

class Oculos extends Produto {
    - tipo: String
    - referencia: String
}

class Acessorio extends Produto {
    - tipo: String
    - nome: String
    - descricao: String
}

class Armacao {
    - material: String
    - tamanho: String
    - formato: String
    - Modelo: String
}

class Medida {
    - aro: Double
    - haste: Double
    - ponte: Double
}

class Lente {
    - tipoLente: String
    - materialLente: String
    - indiceRefracao: Double
    - tratamento: String
    - categoriaFiltroSolar: String
    - grau: String
}

enum StatusProduto {
    DISPONIVEL, INDISPONIVEL
}

class Cor {
    - nome: String
    - indiceCorantes: String
}

enum Categoria {
    MASCULINO, FEMININO, UNISSEX, INFANTIL
}

class Usuario {
    - nome: String
    - cpf: String
    - email: String
    - status: Boolean
}

class Cartao{
    - bandeira: String
    - numero: Double
    - nome: String
}

Enum Permissao {
    ADMIN, USER
}

class Pedido {
    - id: Integer
    - data: LocalDateTime
    - usuario: Usuario
    - precoTotal: Double
}

enum StatusPedido {
    PAGO, ATRASADO, PENDENTE
}

enum FormaPagamento {
    BOLETO, PIX, DEBITO, CREDITO
}

class ItemPedido {
    - quantidade: Integer
    - precoUnitario: Double
}

class Marca {
    - nome: String
}

class Endereco {
    - cep: String
    - estado: String
    - cidade: String
    - bairro: String
    - rua: String
    - numero: Integer
}

Pedido     "*" -->   "1" Usuario
Pedido     "*" -->   "*" ItemPedido
Pedido     "*" -->   "1" FormaPagamento
Pedido     "*" -up-> "1" StatusPedido
ItemPedido "*" -->   "1" Produto
Produto    "*" -left->   "1" StatusProduto

Armacao    "*" -up->   "1" Categoria
Armacao    "*" *-->  "1" Marca
Armacao    "*" o-->  "1" Cor
Armacao    "*" o-->  "1" Medida
Lente      "*" *-->  "1" Marca
Lente      "*" o-->  "1" Cor
Oculos     "*" *-->  "1" Armacao
Oculos     "*" *-->  "1" Lente

Usuario    "1" -->   "*" Permissao
Usuario    "*" -->   "*" Endereco
Usuario    "*" -->   "*" Cartao

@enduml